### ISSUE TITLE
key "orig_quat" not found'

### ISSUE THREAD

**Issue by oxcxsxixbxaxn** [Befzz/blender3d_import_psk_psa#18]
I have a model that was originally exported from umodel (fortnite) but is now in XPS format
It seems to have the original skeleton/bones in tact when I import this into blender, but when I try to import animations from a psa,I get the below:

Is something stripped from the bones? do I need to recreate them somehow? What is the minimum requirement for bones in a model for it to work with PSA import?  I unfortunately have no other way to get the original model as it is no longer in the game...

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 1731, in execute
    error_callback = util_ui_show_msg
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 1185, in psaimport
    armature_obj.pose.bones[orig_name])
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 1145, in new_psa_bone
    psa_bone.orig_quat = Quaternion(bone['orig_quat'])
KeyError: 'bpy_struct[key]: key "orig_quat" not found'

**Comment by Befzz** [comment]
psk:  
1) original skeleton data ( bone rotation and location ) is stored in bone custom property (orig_quat, orig_loc ). So called "bind pose". It is required because bones, when imported is realigned to "look nicer".  

psa:  
When importing animation, the original data(bind pose) is available through the custom property(orig_quat, orig_loc ). Each Blender's keyframe is the "difference" between bindpose and psa-keyframe data.
Without this data, this plugin will not work.  

However. If model that you have is created without "realign bones"(original rotation is used to align bones), it may be possible to import psa over it with correct result, BUT some `programming` is required.

**Comment by Befzz** [comment]
@oxcxsxixbxaxn  Share model(skeleton), and psa file. I'll look at it.

**Comment by oxcxsxixbxaxn** [comment]
thanks, can see those custom properties in other models, but they are indeed missing from this xps import, I'm fairly sure the bones are unchanged in relation to the skeleton, but the scale and overall rotate is out and the names look a bit messed up 

I guess the programming you refer to is to calculate and write these for each bone?  

I have attached the [xps](https://github.com/oxcxsxixbxaxn/3d/blob/master/thanos.xps) and a small [psa](https://github.com/oxcxsxixbxaxn/3d/blob/master/Fortnite_M_Avg_Player_Skeleton_4.psa) which is just a simple one experted from the game.

I've uploaded a blender of just the [skeleton ](https://github.com/oxcxsxixbxaxn/3d/blob/master/thanos-skel.blend) and larger file with the whole [model and skeleton](https://github.com/oxcxsxixbxaxn/3d/blob/master/thanos.blend) in case you don't have the xps import add-on handy.

**Comment by Befzz** [comment]
Oooooookey... this is a best that i can do:  
  
![thanos_cantfix](https://user-images.githubusercontent.com/1160036/47451042-69523f00-d7cf-11e8-8e91-62481a75c115.PNG)

( I have renamed the bones (replaced Space with Underscore) and then applied modified psa import )  
  
I can't get better result, because, AFAIU, .xps importer is reorienting bones to children (so "bind pose" got lost) and i think that .xps data by itself is not looks compatible with .psa data.  
  
Therefore, no correct "bind pose" -> no correct animation.  

It is, probably possible to get good result, but it is require digging in .xps(file format, editing xnalara plugin, lot of tests and time...).

**Comment by oxcxsxixbxaxn** [comment]
Thanks for looking and the explanation, though this model is not usable I learned some things.
Let's close this one.

Thanks
