### ISSUE TITLE
Strange bone orientation from a specific pack of PSK models

### ISSUE THREAD

**Issue by Gnates** [Befzz/blender3d_import_psk_psa#8]
-Blender 2.79 Win64
-Beffz_NoAnim

Hello again, still loving your addon.
I recently came across a problem. I tried importing some models from this Jedi Academy models pack: https://facepunch.com/showthread.php?t=1157665
Image of imported PSK skeleton: https://thumbs.gfycat.com/AppropriateEnviousIndri-max-14mb.gif
-The bones are misaligned, but their bone weights for the mesh appear to be working normally.

Here is 1 model from the pack: https://www.sendspace.com/file/hnd1wd
(If the download link is broken, try this: https://my.mixtape.moe/duuaot.zip )

The game models were originally in .GLM format and were converted to .PSK by a user from the facepunch website linked above.
I've thought about trying the GLM import addon: https://github.com/mrwonko/Blender-2.6-Ghoul-2-addon
but the author stated that it doesn't work with newer versions of Blender.

I'm hoping you might have an idea of what is going on with the PSKs from this pack.
Anyway, I appreciate what you've done already. Thank you.

**Comment by Befzz** [comment]
In the current state: it's not a bug.   
Psk's have information about position and rotation of the bone. But not the "*bone-tail position for blender*".  

Script just choosing best(?) axis(+-X or +-Y or +-Z) depending on a child[ren] position. It's not making additional rotation.  

Because it is not always predictable - where bone must point to (if 1 child or 0 children or 2+ children).   
  
IMO. They should be aligned by psk-maker(skeleton-maker).  

p.s. this psk model have no bone for back part of head ("cranium" vertex group)

**Comment by Gnates** [comment]
You're right about the head, not sure how I didn't see that earlier. 
Is it related to how the model was converted in Noesis? The creation date of the PSK is around 2012, so maybe the conversion software he was using had gone through a bunch of changes since then.
I don't know anything about psk-maker(skeleton-maker), unfortunately.
Anyway, thank you for clarifying.

**Comment by Befzz** [comment]
`Is it related to how the model was converted in Noesis?`  
I don't know :)  

`psk-maker(skeleton-maker)` 
I mean software that was used to create psk or skeleton 😄
